# release pipeline — tag goes brrr and packages hit nuget.org 🚀
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: linux
    steps:
      - name: yoink the code 📥
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: figure out the version from the tag 🏷️
        id: version
        run: |
          # strip the v prefix from the tag — v1.2.3 -> 1.2.3
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          # auto-detect pre-release — if version has a dash its not the final form 🚨
          if [[ "$VERSION" == *-* ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
            echo "version is ${VERSION} (pre-release) — test drop incoming 🧪"
          else
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
            echo "version is ${VERSION} lets gooo 🔥"
          fi

      - name: sanity check — make sure tag matches Directory.Build.props 🧐
        run: |
          props_version=$(grep -oP '(?<=<Version>)[^<]+' Directory.Build.props)
          if [ "$props_version" != "${{ steps.version.outputs.version }}" ]; then
            echo "bruh the tag says ${{ steps.version.outputs.version }} but Directory.Build.props says ${props_version} thats not it 💀"
            exit 1
          fi
          echo "version vibes match — ${props_version} 🔥"

      - name: litty build in release mode 🏗️🔥
        run: dotnet run --project src/LittyLogs.Tool -- build --configuration Release

      - name: litty test one more time for the culture 🧪🔥
        run: dotnet run --project src/LittyLogs.Tool -- test --configuration Release --no-build

      - name: pack all the nupkgs 📦
        run: dotnet pack --configuration Release --no-build --output ./nupkgs

      - name: flex what we packed 💅
        run: ls -la ./nupkgs/

      - name: push to nuget.org — the besties need these packages 🚀
        run: |
          for pkg in ./nupkgs/*.nupkg; do
            echo "pushing ${pkg} to nuget.org no cap 📤"
            dotnet nuget push "$pkg" \
              --api-key "${{ secrets.NUGET_API_KEY }}" \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate
          done

      - name: extract changelog section for this version 📜
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          # extract everything between this version header and the next version header (or EOF)
          NOTES=$(awk "/^## \[${VERSION}\]/{found=1; next} /^## \[/{if(found) exit} found{print}" CHANGELOG.md)
          if [ -z "$NOTES" ]; then
            NOTES="v${VERSION} dropped no cap — check the commits for the full vibe 🔥"
          fi
          {
            echo "notes<<CHANGELOG_EOF"
            echo "$NOTES"
            echo "CHANGELOG_EOF"
          } >> "$GITHUB_OUTPUT"

      - name: create forgejo release — home turf first 🏠🔥
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ steps.changelog.outputs.notes }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          TAG="${{ steps.version.outputs.tag }}"
          NOTES="$RELEASE_NOTES"
          PRERELEASE="${{ steps.version.outputs.prerelease }}"
          API_URL="${GITHUB_SERVER_URL}/api/v1"
          REPO="${GITHUB_REPOSITORY}"
          # create the release
          RELEASE_ID=$(curl -s -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"${TAG}\", \"name\": \"v${VERSION} — new drop 🔥\", \"body\": $(echo "$NOTES" | jq -Rs .), \"prerelease\": ${PRERELEASE}}" \
            "${API_URL}/repos/${REPO}/releases" | jq -r '.id')
          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "bruh forgejo release creation failed 💀"
            exit 1
          fi
          echo "forgejo release created with id ${RELEASE_ID} 🔥"
          # upload the nupkg assets
          for pkg in ./nupkgs/*.nupkg; do
            filename=$(basename "$pkg")
            echo "uploading ${filename} to forgejo release 📤"
            curl -s -X POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@${pkg}" \
              "${API_URL}/repos/${REPO}/releases/${RELEASE_ID}/assets?name=${filename}"
          done
          echo "forgejo release is bussin 🔥"

      - name: create github release on the mirror 🪞
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          RELEASE_NOTES: ${{ steps.changelog.outputs.notes }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          TAG="${{ steps.version.outputs.tag }}"
          PRERELEASE_FLAG=""
          if [ "${{ steps.version.outputs.prerelease }}" = "true" ]; then
            PRERELEASE_FLAG="--prerelease"
          fi
          gh release create "${TAG}" \
            --repo "phsk69/litty-logs-dotnet" \
            --title "v${VERSION} — new drop 🔥" \
            --notes "$RELEASE_NOTES" \
            $PRERELEASE_FLAG \
            ./nupkgs/*.nupkg
